### ISSUE TITLE
能支持自定义JDK版本吗？

### ISSUE THREAD

**Issue by SummerSec** [pen4uin/java-echo-generator#1]

**Comment by pen4uin** [comment]
默认是调 setVersionToJava5  设置的，感觉基本够用了。你是指更低版本？

**Comment by SummerSec** [comment]
> 默认是调 setVersionToJava5 设置的，感觉基本够用了。你是指更低版本？

在gui没有看到可以操作设置的JDK版本的地方，如果默认是jdk5，确实是够用了。
