### ISSUE TITLE
jetty的7.6.16是否并不支持呢

### ISSUE THREAD

**Issue by joonk685** [pen4uin/java-echo-generator#4]
我在jetty的7.6.16利用shiro550并没有成功

**Comment by pen4uin** [comment]
已支持，你自己 pull 最新的代码编译吧。

测试截图：

<img width="1472" alt="image" src="https://github.com/pen4uin/java-echo-generator/assets/55024146/c9c8a4bd-16ad-476b-bd16-6de8570c94be">
